<?php
// echo "<pre>";
// print_r($data);
// echo "</pre>";
// die();

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <title>Edit</title>
</head>
<body>
  <div class="container">
<form action="edit" method="POST">
  <div class="form-group mt-5">
    <label for="exampleFormControlInput1">product-id</label>
    <input type="text" name="id" class="form-control" id="exampleFormControlInput1"  value="<?php echo $data[0]->product_id; ?>" disabled>
    <input type="hidden" name="idd" class="form-control" id="exampleFormControlInput1"  value="<?php echo $data[0]->product_id; ?>">
  </div>
  <div class="form-group mt-5">
    <label for="exampleFormControlInput1">product-name</label>
    <input type="text" name="name" class="form-control" id="exampleFormControlInput1"  value="<?php echo $data[0]->name; ?>">
  </div>
  <div class="form-group mt-5">
    <label for="exampleFormControlInput1">product-category</label>
    <input type="text" name="category" class="form-control" id="exampleFormControlInput1"  value="<?php echo $data[0]->category; ?>">
  </div>
  <div class="form-group mt-5">
    <label for="exampleFormControlInput1">product-Disription</label>
    <input type="text" name="discription" class="form-control" id="exampleFormControlInput1"  value="<?php echo $data[0]->discription; ?>">
  </div>
  <input class="btn btn-success mt-5" name="submit" type="submit" value="submit">

</form>
</div>


<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>