<?php 

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <div class="container mt-5">
<form method="POST" action="/user/submit">

  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input  name="username" type="email" class="form-control" id="exampleInputEmail1" value="<?php echo $user[0]->username; ?>" aria-describedby="emailHelp">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input  name="password" type="text" class="form-control" id="exampleInputPassword1" value="<?php echo $user[0]->password; ?>">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Status</label>
    <input  name="status" type="text" class="form-control" id="exampleInputPassword1" value="<?php echo $user[0]->status; ?>">
  </div>
  <div class="mb-3 form-check">
      <label class="form-check-label" for="exampleCheck1">Id</label>

      <input type="hidden" name="id" value="<?php echo $user[0]->user_id; ?>" >
     <input class="form-control" id="disabledInput" value="<?php echo $user[0]->user_id; ?>"  name="id" type="text" placeholder="Disabled input here..." disabled>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div> 
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>
